### ISSUE TITLE
How to calculate the homography transform?

### ISSUE THREAD

**Issue by HkDzl** [LCAV/LenslessPiCam#95]
Hello, in Chapter 5 of paper "Learned reconstructions for practical mask-based lensless imaging", it is mentioned that a homography transform is needed to co-align both cameras’ coordinate systems when capturing real dataset. Could you please provide more details on how to calculate this homography transform?

**Comment by ebezzam** [comment]
Hi @HkDzl thanks for your question. There are algorithms/libraries for calculating the homography transform, for example [findHomography](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780) from OpenCV. Here's a nice tutorial on how to use this: https://www.geeksforgeeks.org/image-registration-using-opencv-python/

I'm not sure of the exact approach the authors of the paper use,  but from what I understand, they align a reconstruction of points and the corresponding measurement from the lensed camera. The text from their paper says:

> To achieve pixel-wise alignment between the image pairs, we first optically align the two cameras, then further calibrate by displaying a series of points on the computer monitor that span the field-of-view. We reconstruct these point images and compute the homography transform needed to co-align both cameras’ coordinate systems. This transform is applied to all subsequent images.

What I currently do is much simpler because all I care about is aligning my reconstructed image with the original image to then train a reconstruction algorithm. (There is probably a better approach which I why I would still leave this Issue open, and to also justify the approach done here):

1. Measure data with only a lensless camera, as shown in [this paper](https://drive.google.com/file/d/1jd8gmZlJd7YsiaOYaWQ_gmL7q_mcL6_R/view?usp=sharing) (to be published as part of the proceedings of the [2023 Optica Imaging Congress](https://www.optica.org/events/congress/imaging_and_applied_optics_congress/program/computational_optical_sensing_and_imaging/)), and with the procedure described [here](https://lensless.readthedocs.io/en/latest/measurement.html#collecting-arbitrary-dataset). This yields a dataset of lensless RGB measurements, like [this one](https://drive.switch.ch/index.php/s/9NNGCJs3DoBDGlY) of 10K examples from the CelebA dataset with the lensless camera described in the above paper. The reasons for this setup are: (1) simpler (single camera to control, no beamsplitter) and (2) we avoid "imitating" any distortions of the lens as we are directly using the original images as the ground truth. (in the paper you referred to, they also had to correct for these distortions "calibrate the lens distortion using OpenCV’s undistort camera calibration procedure") .
2. Manually align the reconstruction with the original RGB dataset that was displayed on the screen, by [shifting](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L517) a [simulated version](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L515) of the original image and [cropping](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/scripts/recon/train_unrolled.py#L369) the region of interest of both the reconstruction and the simulated version. This simulated version of the original image is obtained by simply rescaling it and padding it according to the physical dimensions of the setup. Simulator is created [here](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L473) and parameters are set [here](https://github.com/LCAV/LenslessPiCam/blob/c244f68bc18e8b82ded107464545e71131c6df78/configs/train_celeba_digicam.yaml#L14).
3. Finally check that the alignment looks alright by trying out some reconstructions, and overlay that on top of the simulated original image, as done [here](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/scripts/recon/train_unrolled.py#L350).

Doing this alignment requires some trial-and-error to find the correct amount of pixels to shift by and the region to crop out. But it only has to be done once, and for the CelebA dataset we've measured, those parameters are the defaults to our [Dataset object](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L389) for loading this dataset. 

Below is an example of aligning the measurement with the ground truth image:

Raw data
![lensless_raw_0](https://github.com/LCAV/LenslessPiCam/assets/4757445/dae17793-c8e8-4e1d-b961-50e3cb0d1142)

Reconstruction
![lensless_recon_0](https://github.com/LCAV/LenslessPiCam/assets/4757445/65bc743c-ac26-49ab-a998-511948c45ca2)

Original image simulated (and shifted) -> ground-truth for training
![lensed_0](https://github.com/LCAV/LenslessPiCam/assets/4757445/35c7d011-5e36-4e1f-baa5-b05c8bced7c6)

Reconstruction and ground-truth cropped and overlaid
![overlay_lensed_recon_0](https://github.com/LCAV/LenslessPiCam/assets/4757445/1e62e1c2-e489-4ffe-9b49-6b31662578f7)

And those outputs (reconstruction and simulated original [both cropped](https://github.com/LCAV/LenslessPiCam/blob/8c4e21e40c57c0daa523692a04a3374bf2913823/lensless/recon/utils.py#L493)) can then be used for training as in "Learned reconstructions for practical mask-based lensless imaging" with [this script](https://github.com/LCAV/LenslessPiCam/blob/main/scripts/recon/train_unrolled.py) and the proper Hydra configuration :rocket: 

NOTE: A lot of this is  work-in-progress in PR https://github.com/LCAV/LenslessPiCam/pull/96, but hopefully will be merged in the next two months (with documentation). But hopefully the above can be helpful for now, and happy to answer any other questions!

**Comment by HkDzl** [comment]
Thank you very much for your very detailed answer.

**Comment by HkDzl** [comment]
> Hi @HkDzl thanks for your question. There are algorithms/libraries for calculating the homography transform, for example [findHomography](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga4abc2ece9fab9398f2e560d53c8c9780) from OpenCV. Here's a nice tutorial on how to use this: https://www.geeksforgeeks.org/image-registration-using-opencv-python/
> 
> I'm not sure of the exact approach the authors of the paper use, but from what I understand, they align a reconstruction of points and the corresponding measurement from the lensed camera. The text from their paper says:
> 
> > To achieve pixel-wise alignment between the image pairs, we first optically align the two cameras, then further calibrate by displaying a series of points on the computer monitor that span the field-of-view. We reconstruct these point images and compute the homography transform needed to co-align both cameras’ coordinate systems. This transform is applied to all subsequent images.
> 
> What I currently do is much simpler because all I care about is aligning my reconstructed image with the original image to then train a reconstruction algorithm. (There is probably a better approach which I why I would still leave this Issue open, and to also justify the approach done here):
> 
> 1. Measure data with only a lensless camera, as shown in [this paper](https://drive.google.com/file/d/1jd8gmZlJd7YsiaOYaWQ_gmL7q_mcL6_R/view?usp=sharing) (to be published as part of the proceedings of the [2023 Optica Imaging Congress](https://www.optica.org/events/congress/imaging_and_applied_optics_congress/program/computational_optical_sensing_and_imaging/)), and with the procedure described [here](https://lensless.readthedocs.io/en/latest/measurement.html#collecting-arbitrary-dataset). This yields a dataset of lensless RGB measurements, like [this one](https://drive.switch.ch/index.php/s/9NNGCJs3DoBDGlY) of 10K examples from the CelebA dataset with the lensless camera described in the above paper. The reasons for this setup are: (1) simpler (single camera to control, no beamsplitter) and (2) we avoid "imitating" any distortions of the lens as we are directly using the original images as the ground truth. (in the paper you referred to, they also had to correct for these distortions "calibrate the lens distortion using OpenCV’s undistort camera calibration procedure") .
> 2. Manually align the reconstruction with the original RGB dataset that was displayed on the screen, by [shifting](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L517) a [simulated version](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L515) of the original image and [cropping](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/scripts/recon/train_unrolled.py#L369) the region of interest of both the reconstruction and the simulated version. This simulated version of the original image is obtained by simply rescaling it and padding it according to the physical dimensions of the setup. Simulator is created [here](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L473) and parameters are set [here](https://github.com/LCAV/LenslessPiCam/blob/c244f68bc18e8b82ded107464545e71131c6df78/configs/train_celeba_digicam.yaml#L14).
> 3. Finally check that the alignment looks alright by trying out some reconstructions, and overlay that on top of the simulated original image, as done [here](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/scripts/recon/train_unrolled.py#L350).
> 
> Doing this alignment requires some trial-and-error to find the correct amount of pixels to shift by and the region to crop out. But it only has to be done once, and for the CelebA dataset we've measured, those parameters are the defaults to our [Dataset object](https://github.com/LCAV/LenslessPiCam/blob/5892fba0db9b24d195aed4f55609fc9a8fb37732/lensless/utils/dataset.py#L389) for loading this dataset.
> 
> Below is an example of aligning the measurement with the ground truth image:
> 
> Raw data ![lensless_raw_0](https://user-images.githubusercontent.com/4757445/273977417-dae17793-c8e8-4e1d-b961-50e3cb0d1142.png)
> 
> Reconstruction ![lensless_recon_0](https://user-images.githubusercontent.com/4757445/273977538-65bc743c-ac26-49ab-a998-511948c45ca2.png)
> 
> Original image simulated (and shifted) -> ground-truth for training ![lensed_0](https://user-images.githubusercontent.com/4757445/273977623-35c7d011-5e36-4e1f-baa5-b05c8bced7c6.png)
> 
> Reconstruction and ground-truth cropped and overlaid ![overlay_lensed_recon_0](https://user-images.githubusercontent.com/4757445/273977959-1e62e1c2-e489-4ffe-9b49-6b31662578f7.png)
> 
> And those outputs (reconstruction and simulated original [both cropped](https://github.com/LCAV/LenslessPiCam/blob/8c4e21e40c57c0daa523692a04a3374bf2913823/lensless/recon/utils.py#L493)) can then be used for training as in "Learned reconstructions for practical mask-based lensless imaging" with [this script](https://github.com/LCAV/LenslessPiCam/blob/main/scripts/recon/train_unrolled.py) and the proper Hydra configuration 🚀
> 
> NOTE: A lot of this is work-in-progress in PR #96, but hopefully will be merged in the next two months (with documentation). But hopefully the above can be helpful for now, and happy to answer any other questions!

Thank you very much for your very detailed answer.

**Comment by ebezzam** [comment]
I've prepared another example here: https://colab.research.google.com/drive/1c6kUbiB5JO1vro0-IMd-YDDP1g7NFXv3#scrollTo=MtN7GWCIrBKr

I will close this issue.
